kind: pipeline
name: deploy CV

steps:
  - name: build
    image: aergus/latex
    pull: always
    commands:
      - make

  - name: deploy
    image: appleboy/drone-scp
    settings:
      source: /drone/src/*.pdf
      strip_components: 2 # Make sure the tarball doesn't contain leading path
      rm: true # Make sure only the newly generated files are left
      host:
        from_secret: ssh_host
      target:
        from_secret: ssh_target
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: notify
    image: plugins/matrix
    settings:
      homeserver:
        from_secret: matrix_homeserver
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
      trigger:
        status:
          - failure
          - success
