kind: pipeline
type: exec
name: deploy CV

steps:
- name: build
  commands:
  - nix build

- name: check
  commands:
  - nix flake check

- name: deploy
  commands:
  - nix run github:ambroisie/nix-config#drone-rsync
  environment:
    # Use trailing slash to sync to folder's *content* to the target
    SYNC_SOURCE: 'result/share/'
    SYNC_HOST:
      from_secret: ssh_host
    SYNC_TARGET:
      from_secret: ssh_target
    SYNC_USERNAME:
      from_secret: ssh_user
    SYNC_KEY:
      from_secret: ssh_key
    SYNC_PORT:
      from_secret: ssh_port
  when:
    branch:
      - main
    event:
      exclude:
        - pull_request


- name: notifiy
  commands:
  - nix run github:ambroisie/matrix-notifier
  environment:
    ADDRESS:
      from_secret: matrix_homeserver
    ROOM:
      from_secret: matrix_roomid
    USER:
      from_secret: matrix_username
    PASS:
      from_secret: matrix_password
  when:
    status:
    - failure
    - success
